#ifndef QZ_INTERRUPT_LIST_H
#define QZ_INTERRUPT_LIST_H

#define INTERRUPT_OFFSET 0x20


#define TIMER_INTERRUPT INTERRUPT_OFFSET + 0x00
#define KEYBOARD_INTERRUPT INTERRUPT_OFFSET + 0x01

#endif // !QZ_INTERRUPT_LIST_H
